name: Android Lint

on:
    push:
    pull_request:
    workflow_dispatch:

jobs:
    lint:
        runs-on: codeberg-medium

        steps:
            - name: Checkout repository
              uses: actions/checkout@v5

            - name: Setup JDK
              uses: actions/setup-java@v5
              with:
                  java-version: 17
                  distribution: temurin
                  cache: gradle

            - name: Lint
              run: ./gradlew lintDebug
