name: "💡 Feature Request"
description: Suggest a new feature/enhancement for this project
labels: [ "enhancement" ]
body:
    -   type: textarea
        id: feature-explanation
        attributes:
            label: Feature explanation
            description: Brief explanation of what you want to be added
        validations:
            required: true

    -   type: textarea
        id: additional-context
        attributes:
            label: Additional context
            description: Implementation guidance, screenshots/examples, etc
        validations:
            required: false

    -   type: checkboxes
        id: confirmation
        attributes:
            label: Prerequisites
            options:
                -   label: "I've checked existing issues to see if this already was requested"
                    required: true
                -   label: "I've ensured I am on the LATEST app version in case this was already added recently"
                    required: true
